name: my_restaurant
description: restaurant app to order food
publish_to: 'none'
version: 1.4.0+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  image_picker: 0.6.7+14
  shared_preferences: 0.5.12+4
  select_form_field: 1.0.1
  firebase_storage: 5.1.0
  firebase_core: 0.5.2+1
  firebase_analytics: 6.2.0
  url_launcher: 5.7.10
  flutter_launcher_icons: 0.8.1
  graphql_flutter: ^4.0.1
  provider: 4.3.3

flutter_icons:
  android: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#FFF0C9"
  adaptive_icon_foreground: "assets/icons/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: 1.9.2

flutter:
  uses-material-design: true

  assets:
    - assets/icons/icon.png

  fonts:
    - family: ReliqStd-Active
      fonts:
        - asset: assets/fonts/ReliqStd-Active.otf
    - family: Lato-Regular
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400